name: Picus Full CI/CD

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:

  ecs:
    name: Deploy ECS API
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Configure AWS
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-central-1

      - name: Login to ECR
        uses: aws-actions/amazon-ecr-login@v2

      - name: Build & Push Image (AMD64)
        run: |
          docker buildx create --use
          docker buildx build \
            --platform linux/amd64 \
            -t ${{ secrets.ECR_REPO }}:latest \
            --push ./app

      - name: Deploy ECS Task
        uses: aws-actions/amazon-ecs-deploy-task-definition@v2
        with:
          task-definition: infra/terraform/picus-taskdef.json
          service: picus-service
          cluster: picus-cluster
          wait-for-service-stability: true


  lambda:
    name: Deploy Lambda Delete API
    runs-on: ubuntu-latest
    needs: ecs

    steps:
      - uses: actions/checkout@v4

      - name: Configure AWS
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-central-1

      - name: Install Serverless
        run: |
          npm install -g serverless
          cd serverless-delete && npm install

      - name: Deploy Lambda
        run: |
          cd serverless-delete
          serverless deploy


  terraform:
    name: Terraform Plan
    needs: ecs
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: hashicorp/setup-terraform@v2

      - name: Terraform Init
        run: terraform -chdir=infra/terraform init

      - name: Terraform Plan
        run: terraform -chdir=infra/terraform plan
