name: Picus Infra Deploy (Terraform Apply)

on:
  workflow_dispatch:
    inputs:
      confirm:
        description: "Bu action Terraform APPLY çalıştırır. Onay için 'yes' yaz."
        required: true
        default: "no"

jobs:
  terraform-apply:
    if: ${{ github.event.inputs.confirm == 'yes' }}
    runs-on: ubuntu-latest

    env:
      AWS_REGION: ${{ secrets.AWS_REGION }}

    defaults:
      run:
        working-directory: infra/terraform

    steps:
      # 1) Kodu çek
      - name: Checkout repository
        uses: actions/checkout@v4

      # 2) Terraform kurulumu
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.9.5

      # 3) AWS credentials
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      # 4) Terraform fmt check
      - name: Terraform fmt
        run: terraform fmt -check -recursive

      # 5) Terraform init (backend = TRUE → gerçek state)
      - name: Terraform init
        run: terraform init

      # 6) Terraform validate
      - name: Terraform validate
        run: terraform validate

      # 7) Terraform plan (sadece önizleme, apply'dan önce ne yapacağını gör)
      - name: Terraform plan
        run: terraform plan -input=false -var="acm_certificate_arn=${{ secrets.ACM_CERT_ARN }}"


      # 8) Terraform apply
      - name: Terraform apply
        run: terraform apply -input=false -auto-approve -var="acm_certificate_arn=${{ secrets.ACM_CERT_ARN }}"
