name: Picus Infra CI (Terraform)

on:
  push:
    branches: ["main"]
    paths:
      - "infra/**"
      - ".github/workflows/infra-ci.yml"

jobs:
  terraform-validate-plan:
    runs-on: ubuntu-latest

    env:
      AWS_REGION: ${{ secrets.AWS_REGION }}

    defaults:
      run:
        working-directory: infra/terraform

    steps:
      # 1) Kodu çek
      - name: Checkout repository
        uses: actions/checkout@v4

      # 2) Terraform kurulumu
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.9.5

      # 3) AWS credentials (Terraform için de lazım)
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      # 4) terraform fmt check
      - name: Terraform fmt
        run: terraform fmt -check -recursive

      # 5) terraform init
      - name: Terraform init
        run: terraform init -backend=false

      # 6) terraform validate
      - name: Terraform validate
        run: terraform validate

      # 7) terraform plan (sadece görmek için, apply yok)
      - name: Terraform plan
        run: terraform plan -input=false -lock=false

